In [1]:
import numpy as np

tokens = ["low", "est", "</w>"]

print("BPE Tokens:")
print(tokens)

vocabulary = sorted(set(tokens))

print("\nVocabulary:")
print(vocabulary)

token_to_id = {}

for index, token in enumerate(vocabulary):
    token_to_id[token] = index

print("\nToken to ID:")
print(token_to_id)

token_ids = []

for token in tokens:
    token_ids.append(token_to_id[token])

token_ids = np.array(token_ids)

print("\nToken IDs:")
print(token_ids)

embedding_size = 5

embedding_matrix = np.random.rand(len(vocabulary), embedding_size)

print("\nEmbedding Matrix:")
print(embedding_matrix)

embedded_tokens = embedding_matrix[token_ids]

print("\nEmbedded Tokens:")
print(embedded_tokens)

context_vector = np.sum(embedded_tokens, axis=0)

print("\nContext Vector:")
print(context_vector)

scores = context_vector[:len(vocabulary)]

exp_scores = np.exp(scores)

probabilities = exp_scores / np.sum(exp_scores)

print("\nSoftmax Probabilities:")
print(probabilities)

BPE Tokens:
['low', 'est', '</w>']

Vocabulary:
['</w>', 'est', 'low']

Token to ID:
{'</w>': 0, 'est': 1, 'low': 2}

Token IDs:
[2 1 0]

Embedding Matrix:
[[0.02843459 0.53555766 0.53182833 0.76895755 0.61082893]
 [0.01077439 0.10741954 0.17794862 0.32917154 0.33293598]
 [0.83060021 0.14579799 0.12679645 0.62944659 0.44317969]]

Embedded Tokens:
[[0.83060021 0.14579799 0.12679645 0.62944659 0.44317969]
 [0.01077439 0.10741954 0.17794862 0.32917154 0.33293598]
 [0.02843459 0.53555766 0.53182833 0.76895755 0.61082893]]

Context Vector:
[0.86980919 0.7887752  0.8365734  1.72757567 1.38694461]

Softmax Probabilities:
[0.3460839  0.31914554 0.33477057]
